export const members = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    email: "John@gamil.com",
    city: "New York",
    mobile: "0177738323",
  },
  {
    id: 2,
    first_name: "Jane",
    last_name: "Smith",
    email: "Jane@gamil.com",
    city: "Los Angeles",
    mobile: "0177738323",
  },
  {
    id: 3,
    first_name: "Bob",
    last_name: "Johnson",
    email: "Bob@gamil.com",
    city: "Chicago",
    mobile: "0177738323",
  },
  {
    id: 4,
    first_name: "Alice",
    last_name: "Williams",
    email: "Alice@gamil.com",
    city: "San Francisco",
    mobile: "0177738323",
  },
  {
    id: 5,
    first_name: "Charlie",
    last_name: "Brown",
    email: "Charlie@gamil.com",
    city: "Seattle",
    mobile: "0177738323",
  },
  {
    id: 6,
    first_name: "Eva",
    last_name: "Davis",
    email: "Eva@gamil.com",
    city: "Boston",
    mobile: "0177738323",
  },
  {
    id: 7,
    first_name: "Frank",
    last_name: "Miller",
    email: "Frank@gamil.com",
    city: "Austin",
    mobile: "0177738323",
  },
  {
    id: 8,
    first_name: "Grace",
    last_name: "Turner",
    email: "Grace@gamil.com",
    city: "Denver",
    mobile: "0177738323",
  },
  {
    id: 9,
    first_name: "Henry",
    last_name: "Taylor",
    email: "Henry@gamil.com",
    city: "Miami",
    mobile: "0177738323",
  },
  {
    id: 10,
    first_name: "Ivy",
    last_name: "Carter",
    email: "Ivy@gamil.com",
    city: "Atlanta",
    mobile: "0177738323",
  },
];

export const bazarList = [
  { id: 1, name: "Alice Johnson", amount: 325, date: "12 Nov 2023" },
  { id: 2, name: "Bob Smith", amount: 330, date: "14 Nov 2023" },
  { id: 3, name: "Charlie Davis", amount: 328, date: "16 Nov 2023" },
  { id: 4, name: "David Brown", amount: 335, date: "17 Nov 2023" },
  { id: 5, name: "Eva Williams", amount: 327, date: "18 Nov 2023" },
  { id: 6, name: "Frank Taylor", amount: 332, date: "19 Nov 2023" },
  { id: 7, name: "Grace Miller", amount: 329, date: "20 Nov 2023" },
  { id: 8, name: "Henry Turner", amount: 331, date: "22 Nov 2023" },
  { id: 9, name: "Ivy Carter", amount: 326, date: "25 Nov 2023" },
  { id: 10, name: "Jackie Harris", amount: 333, date: "25 Nov 2023" },
];
export const mealList = [
  { id: 1, name: "Alice Johnson", meai_calculation: 175, date: "12 Nov 2023" },
  { id: 2, name: "Bob Smith", meai_calculation: 170, date: "14 Nov 2023" },
  { id: 3, name: "Charlie Davis", meai_calculation: 178, date: "16 Nov 2023" },
  { id: 4, name: "David Brown", meai_calculation: 175, date: "17 Nov 2023" },
  { id: 5, name: "Eva Williams", meai_calculation: 177, date: "18 Nov 2023" },
  { id: 6, name: "Frank Taylor", meai_calculation: 172, date: "19 Nov 2023" },
  { id: 7, name: "Grace Miller", meai_calculation: 179, date: "20 Nov 2023" },
  { id: 8, name: "Henry Turner", meai_calculation: 171, date: "22 Nov 2023" },
  { id: 9, name: "Ivy Carter", meai_calculation: 176, date: "25 Nov 2023" },
  { id: 10, name: "Jackie Harris", meai_calculation: 173, date: "25 Nov 2023" },
];

export const users = [
  {
    id: 1,
    name: "John",
    phone_Number: "0177738323",
    email: "John@gamil.com",
    city: "New York",
  },
  {
    id: 2,
    name: "Jane",
    phone_Number: "0177738323",
    email: "Jane@gamil.com",
    city: "Los Angeles",
  },
  {
    id: 3,
    name: "Bob",
    phone_Number: "0177738323",
    email: "Bob@gamil.com",
    city: "Chicago",
  },
  {
    id: 4,
    name: "Alice",
    phone_Number: "0177738323",
    email: "Alice@gamil.com",
    city: "San Francisco",
  },
  {
    id: 5,
    name: "Charlie",
    phone_Number: "0177738323",
    email: "Charlie@gamil.com",
    city: "Seattle",
  },
  {
    id: 6,
    name: "Eva",
    phone_Number: "0177738323",
    email: "Eva@gamil.com",
    city: "Boston",
  },
  {
    id: 7,
    name: "Frank",
    phone_Number: "0177738323",
    email: "Frank@gamil.com",
    city: "Austin",
  },
  {
    id: 8,
    name: "Grace",
    phone_Number: "0177738323",
    email: "Grace@gamil.com",
    city: "Denver",
  },
  {
    id: 9,
    name: "Henry",
    phone_Number: "0177738323",
    email: "Henry@gamil.com",
    city: "Miami",
  },
  {
    id: 10,
    name: "Ivy",
    phone_Number: "0177738323",
    email: "Ivy@gamil.com",
    city: "Atlanta",
  },
];
